### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by tpirate** [iltekin/dahi-anlamindaki-de#1]
Sitede her sey client side calistigindan cevaplar data.js'ten direk bulunabiliyor. Ayni zamanda backend'de tutulmasi gereken degerler js ile frontend'de tutuldugundan degerler kolayca manipule edilebiliyor. Kotu programlama ig

**Comment by iltekin** [comment]
> Sitede her sey client side calistigindan cevaplar data.js'ten direk bulunabiliyor. Ayni zamanda backend'de tutulmasi gereken degerler js ile frontend'de tutuldugundan degerler kolayca manipule edilebiliyor. Kotu programlama ig

Bu zaten açık kaynak kodlu ve sadece client tarafında çalışması için tasarlanmış bir web sitesi. Resmi bir belge üretilmiyor, hiçbir veri kaydedilmiyor, bir veritabanı yok, backend yok.
